default:
  image: ubuntu:latest

deploy-dev:
  only:
    - main
  stage: deploy
  before_script:
    - ls -la
    - pwd
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_KEY_EC2
    - echo "$(cat $SSH_KEY_EC2)" >> ~/.ssh/ssh-key.pem
    - chmod 400 ~/.ssh/ssh-key.pem
    - cat ~/.ssh/ssh-key.pem
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - >- 
      ssh -i ~/.ssh/ssh-key.pem ubuntu@$EC2_ADDRESS \
      'git config --global --replace-all user.name "xneklyudx"
      && git config --global --replace-all user.email ""
      '
    - >-
      ssh -i ~/.ssh/ssh-key.pem ubuntu@$EC2_ADDRESS \
      '
      ls -la &&
      if [ -d chain_etl ]; 
      then cd chain_etl
      && git status
      && git restore .env
      && git pull --rebase
      && git status
      && sed -i s:%AIRFLOW_UID%:'"$(id -u)"':g .env
      && sed -i s:%AIRFLOW_GID%:0:g .env
      && sed -i s:%_AIRFLOW_WWW_USER_USERNAME%:'"$_AIRFLOW_WWW_USER_USERNAME"':g .env
      && sed -i s:%_AIRFLOW_WWW_USER_PASSWORD%:'"$_AIRFLOW_WWW_USER_PASSWORD"':g .env
      else cd /home/ubuntu && echo "$GITLAB_PASSWORD" >> 1.txt && echo "$GITLAB_USERNAME" >> 2.txt; 
      fi';
    - >-
      ssh -i ~/.ssh/ssh-key.pem ubuntu@$EC2_ADDRESS \
      'cd chain_etl &&
      if [ docker ps | grep -q keyword ]; 
      then docker-compose down && docker-compose up -d --build; 
      else docker-compose up -d --build; 
      fi;'