version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: server --address ":9000" /data
    expose:
      - "9000"
      - "9001"
    hostname: minio
    volumes:
      - data1/:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      predictor_network:
        ipv4_address: 172.5.0.5
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  data1:


networks:
  predictor_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.5.0.0/16
         gateway: 172.5.0.1